name: Build and Publish .NET Application

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src

      - name: Build the application
        run: dotnet build --configuration Release
        working-directory: src

      - name: Publish the application (linux-x64)
        run: dotnet publish --runtime linux-x64 --configuration Release --output ./OpenConnect.NC.SSO-linux-x64
        working-directory: src

      - name: Publish the application (win-x64)
        run: dotnet publish --runtime win-x64 --configuration Release --output ./OpenConnect.NC.SSO-win-x64
        working-directory: src

      - name: Publish the application (osx-arm64)
        run: dotnet publish --runtime osx-arm64 --configuration Release --output ./OpenConnect.NC.SSO-osx-arm64
        working-directory: src

      - name: Compress artifacts
        run: |
          tar czvf OpenConnect.NC.SSO-linux-x64.tar.gz ./src/OpenConnect.NC.SSO-linux-x64/
          tar czvf OpenConnect.NC.SSO-osx-arm64.tar.gz ./src/OpenConnect.NC.SSO-osx-arm64/
          zip -r OpenConnect.NC.SSO-win-x64.zip ./src/OpenConnect.NC.SSO-win-x65/. ./src/OpenConnect.NC.SSO-win-x64/
          ls

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2.2.1
        with:
          fail_on_unmatched_files: true
          files: |
            ./OpenConnect.NC.SSO-linux-x64.tar.gz
            ./OpenConnect.NC.SSO-osx-arm64.tar.gz
            ./OpenConnect.NC.SSO-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_RELEASE_TOKEN }}

      - name: Publish Release Notes
        run: |
          echo "Release for $GITHUB_REF created!"
