name: Build and Publish .NET Application

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore
        working-directory: src

      - name: Build the application
        run: dotnet build --configuration Release
        working-directory: src

      - name: Publish the application (linux-x64)
        run: dotnet publish --runtime linux-x64 --configuration Release --output ./OpenConnect.NC.SSO-linux-x64
        working-directory: src

      - name: Publish the application (win-x64)
        run: dotnet publish --runtime win-x64 --configuration Release --output ./OpenConnect.NC.SSO-win-x64
        working-directory: src

      - name: Publish the application (osx-arm64)
        run: dotnet publish --runtime osx-arm64 --configuration Release --output ./OpenConnect.NC.SSO-osx-arm64
        working-directory: src

      - name: Upload the compressed application (linux-x64)
        uses: actions/upload-artifact@v4.6.2
        with:
          name: OpenConnect.NC.SSO-linux-x64
          path: ./src/OpenConnect.NC.SSO-linux-x64
          include-hidden-files: true

      - name: Upload the compressed application (win-x64)
        uses: actions/upload-artifact@v4.6.2
        with:
          name: OpenConnect.NC.SSO-win-x64
          path: ./src/OpenConnect.NC.SSO-win-x64
          include-hidden-files: true

      - name: Upload the compressed application (osx-arm64)
        uses: actions/upload-artifact@v4.6.2
        with:
          name: OpenConnect.NC.SSO-osx-arm64
          path: ./src/OpenConnect.NC.SSO-osx-arm64
          include-hidden-files: true

      - name: Download Artifact (linux-x64)
        uses: actions/download-artifact@v4
        with:
          name: OpenConnect.NC.SSO-linux-x64
          path: OpenConnect.NC.SSO-linux-x64.zip

      - name: Download Artifact (osx-arm64)
        uses: actions/download-artifact@v4
        with:
          name: OpenConnect.NC.SSO-osx-arm64
          path: OpenConnect.NC.SSO-osx-arm64.zip

      - name: Download Artifact (win-x64)
        uses: actions/download-artifact@v4
        with:
          name: OpenConnect.NC.SSO-win-x64
          path: OpenConnect.NC.SSO-win-x64.zip

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2.2.1
        with:
          fail_on_unmatched_files: true
          files: |
            ${{ GITHUB_WORKSPACE }}/OpenConnect.NC.SSO-linux-x64.zip
            ${{ GITHUB_WORKSPACE }}/OpenConnect.NC.SSO-osx-arm64.zip
            ${{ GITHUB_WORKSPACE }}/OpenConnect.NC.SSO-win-x64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_RELEASE_TOKEN }}

      - name: Publish Release Notes
        run: |
          echo "Release for $GITHUB_REF created!"
